'package: account':
  - packages/account/*
  - packages/account/**/*

'package: block':
  - packages/block/*
  - packages/block/**/*

'package: blockchain':
  - packages/blockchain/*
  - packages/blockchain/**/*

'package: common':
  - packages/common/*
  - packages/common/**/*

'package: tx':
  - packages/tx/*
  - packages/tx/**/*

'package: vm':
  - packages/vm/*
  - packages/vm/**/*
