version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

aliases:
  - &defaults
    working_directory: ~/project/ethereumjs-vm
    docker:
      - image: circleci/node:8
  - &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - node8-{{ checksum "package.json" }}

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save node_modules cache
          key: node8-{{ checksum "package.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - ethereumjs-vm/
  coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - *restore_node_modules
      - run:
          name: coverage
          command: npm run coverage
      - codecov/upload:
          file: ./coverage/lcov.info
          flags: vm

workflows:
  version: 2
  install-and-coverage:
    jobs:
      - install
      - coverage:
          requires:
            - install
