name: 'VM Lint'
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - uses: actions/checkout@v1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node8-${{ hashFiles('**/package.json') }}

      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - run: npm run lint
        env:
          CI: true
