name: 'VM Nightly Test' # without caching
on:
  schedule:
    - cron: '0 0 * * *' # once a day at midnight
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run test:API
        env:
          CI: true
      - run: npm run test:API:browser
        env:
          CI: true

  test-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run test:state:allForks
        env:
          CI: true

  test-blockchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run test:blockchain
        env:
          CI: true

  slow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run test:state:slow
        env:
          CI: true
